package com.sqcw.mylyrics.exampledata

import com.sqcw.mylyrics.models.SongModel

var songs = mutableListOf(
    SongModel(
        0,
        "Au Revoir",
        "Mark Forster feat. Sido",
        "BAUCH UND KOPF",
        "In diesem Haus, wo ich wohn'\nHier ist alles so gewohnt\nSo zum Kotzen vertraut\nMann, jeder Tag ist so gleich\nIch zieh' Runden durch mein' Teich\nIch will nur noch hier raus\nIch brauch' mehr Platz und frischen Wind\nIch muss schnell woanders hin\nSonst wachs' ich hier fest\nIch mach' 'nen Kopfsprung durch die Tür\nIch lass' alles hinter mir\nHab' was Großes im Visier\nIch komm' nie zurück zu mir\n\nEs gibt nichts, was mich hält, au revoir\nVergesst, wer ich war\nVergesst meinen Nam'n\nEs wird nie mehr sein, wie es war\nIch bin weg, au, au\nAu, au, au revoir\nAu, au, au, au, au revoir\nAu, au, au, au\nAu revoir\nAu, au, au, au\nAu revoir, au, au, au, au\n\nAuf Wiederseh'n? Auf kein'\nIch hab' meine Sachen gepackt, ich hau' rein\nSonst wird das für mich immer nur dieser Traum bleiben\nIch brauch' Freiheit, ich geh' auf Reisen\nIch mach' alles das, was ich verpasst hab'\nFahr' mit 'nem Gummiboot bis nach Alaska\nIch spring' in Singapur in das kalte Wasser\nIch such' das Weite und dann tank' ich neue Kraft da\nIch seh' Orte, von den' andere nie hörten\nIch fühl' mich wie Humboldt oder Steve Irwin\nIch setz' mich im Dschungel auf den Maya-Thron\nAuf den Spuren von Messner, Indiana Jones\nDer Phönix macht jetzt 'n Abflug\nAu revoir, meine Freunde, macht's gut\nIch sag' dem alten Leben Tschüss, Affe tot, Klappe zu\nWie die Kinder in Indien, ich mach' 'n Schuh\n\nEs gibt nichts, was mich hält, au revoir\nVergesst, wer ich war\nVergesst meinen Nam'n\nEs wird nie mehr sein, wie es war\nIch bin weg, au, au\nAu, au, au revoir\nAu, au, au, au, au revoir\nAu, au, au, au, au revoir\nAu, au, au, au, au, au\n\nEs gibt nichts, was mich hält, au revoir\nAu, au, au revior\nAu, au, au revior, au, au\nEs wird nie mehr sein, wie es war\nAu, au, ich bin weg, au, au\nAu, au, au revoir\nAu, au, au, au, au revoir\nAu, au, au, au, au revoir\nAu, au, au, au, au revoir\nAu, au, au, au"
    ),
    SongModel(
        0,
        "Flash mich",
        "Mark Forster",
        "BAUCH UND KOPF",
        "Wir sind schon ein, zwei Jahre zusammen und haben schon drei, vier Sachen erlebt\nDoch bist du nur 5 Minuten mal weg, ist das wie 10 Jahre Knast für mich\nEy du wickelst mich zu leicht um deinen Finger, wenn du durch deine blauen Augen guckst wie immer\n\nIch bin hypnotisiert, wenn du vorbei spazierst und es wird jeden Tag ein kleines bisschen schlimmer\nFlash mich nochmal, als wär's das erste mal\nBaby, Baby crash mich so oft du willst, ja bis ich nicht mehr kann\nUnd seit du da bist sind alle Lichter an\nDu machst, dass ich nicht mehr schlafen kann\nIch sehe uns zwei in alt und grau, mit weißen Haaren und dickem Bauch\n\nFlash mich nochmal, als wär's das erste mal, yeah\nWir haben schon ein, zwei Kriege geführt und haben schon drei, vier Zimmer demoliert\nAber weil 5 Minuten ohne dich zu viel sind, bin ich auch mit Nueunzig immer noch bei dir\nEy du wickelst mich so leicht um deinen Finger, wenn du durch deine langen Haare fährst wie immer\n\nIch werd' unkontrolliert, wenn du vorbei spazierst und es wird jeden Tag ein kleines bisschen schlimmer\nFlash mich nochmal, als wär's das erste mal\nBaby, Baby crash mich so oft du willst ja bis ich nicht mehr kann\nUnd seit du da bist sind alle Lichter an\nDu machst, dass ich nicht mehr schlafen kann\nIch sehe uns zwei in alt und grau, mit weißen Haaren und dickem Bauch\n\nFlash mich nochmal, als wär's das erste mal.\nUnd seit du da bist sind alle Lichter an.\nDu machst, dass ich nicht mehr schlafen kann.\nIch sehe uns zwei in alt und grau, mit weißen Haaren und dickem Bauch.\nFlash mich nochmal\nFlash mich nochmal.\nIch sehe uns zwei in alt und grau, mit weißen Haaren und dickem Bauch.\nFlash mich nochmal, als wär's das erste mal."
    ),
    SongModel(
        0,
        "I See Fire",
        "Ed Sheeran",
        "X",
        "Oh, misty eye of the mountain below\nKeep careful watch of my brothers' souls\nAnd should the sky be filled with fire and smoke\nKeep watching over Durin's sons\n\nIf this is to end in fire\nThen we should all burn together\nWatch the flames climb high into the night\n\nCalling out for the rope\nStand by and we will\nWatch the flames burn on and on\nThe mountain side, hey\n\nAnd if we should die tonight\nThen we should all die together\nRaise a glass of wine for the last time\n\nCalling out for the rope\nPrepare as we will\nWatch the flames burn on and on\nThe mountain side\nDesolation comes upon the sky\n\nNow I see fire\nInside the mountain\nAnd I see fire\nBurning the trees\nAnd I see fire\nHollowing souls\nAnd I see fire\nBlood in the breeze\nAnd I hope that you remember me\n\nOh, should my people fall\nThen surely I'll do the same\nConfined in mountain halls\nWe got too close to the flame\n\nCalling out for the rope\nHold fast and we will\nWatch the flames burn on and on\nThe mountain side\nDesolation comes upon the sky\n\nNow I see fire\nInside the mountain\nAnd I see fire\nBurning the trees\nAnd I see fire\nHollowing souls\nAnd I see fire\nBlood in the breeze\nAnd I hope that you remember me\n\nAnd if the night is burning\nI will cover my eyes\nFor if the dark returns\nThen my brothers will die\nAnd as the sky is falling down\nIt crashed into this lonely town\nAnd with that shadow upon the ground\nI hear my people screaming out\n\nNow I see fire\nInside the mountains\nI see fire\nBurning the trees\nI see fire\nHollowing souls\nI see fire\nBlood in the breeze\nI see fire\nOh you know I saw a city burning out (fire)\nAnd I see fire\nFeel the heat upon my skin, yeah (fire)\nAnd I see fire (fire)\nAnd I see fire burn on and on the mountain side"
    ),
    SongModel(
        0,
        "Kings & Queens",
        "Ava Max",
        "Stand Alone",
        "If all of the kings had their queens on the throne\nWe would pop champagne and raise a toast\nTo all of the queens who are fighting alone\nBaby, you're not dancing on your own\n\nCan't live without me you wanna, but you can't, nah-nah-nah\nThink it's funny, but honey, can't run this show on your own\nI can feel my body shake, there's only so much I can take\nI'll show you how a real queen behaves\n\n(Ah) No damsel in distress, don't need to save me\nOnce I start breathing fire, you can't tame me\nAnd you might think I'm weak without a sword\nBut if I had one, it'd be bigger than yours\n\nIf all of the kings had their queens on the throne\nWe would pop champagne and raise a toast\nTo all of the queens who are fighting alone\nBaby, you're not dancing on your own\n\nDisobey me, then baby, it's off with your head\nGonna change it and make it a world you won't forget\n\nNo damsel in distress, don't need to save me\nOnce I start breathing fire, you can't tame me\nAnd you might think I'm weak without a sword\nBut I'm stronger than I ever was before\n\nIf all of the kings had their queens on the throne\nWe would pop champagne and raise a toast\nTo all of the queens who are fighting alone\nBaby, you're not dancing on your own\n\nIn chess, the king can move one space at a time\nBut queens are free to go wherever they like\nYou get too close, you'll get a royalty high\nSo breathe in to feel alive\n\nIf all of the kings had their queens on the throne\nWe would pop champagne and raise a toast\nTo all of the queens who are fighting alone\nBaby, you're not dancing on your own"
    ),
    SongModel(
        0,
        "Numb",
        "Linkin Park",
        "METEORA",
        "I'm tired of being what you want me to be\nFeeling so faithless lost under the surface\nDon't know what you're expecting of me\nPut under the pressure of walking in your shoes\n(Caught in the undertow just caught in the undertow)\nEvery step that I take is another mistake to you\n(Caught in the undertow just caught in the undertow)\n\nI've become so numb I can't feel you there\nBecome so tired so much more aware\nI'm becoming this all I want to do\nIs be more like me and be less like you\n\nCan't you see that you're smothering me\nHolding too tightly afraid to lose control\nCause everything that you thought I would be\nHas fallen apart right in front of you\n(Caught in the undertow just caught in the undertow)\nEvery step that I take is another mistake to you\n(Caught in the undertow just caught in the undertow)\nAnd every second I waste is more than I can take\n\nI've become so numb I can't feel you there\nBecome so tired so much more aware\nI'm becoming this all I want to do\nIs be more like me and be less like you\n\nAnd I know\nI may end up failing too\nBut I know\nYou were just like me with someone disappointed in you\n\nI've become so numb I can't feel you there\nBecome so tired so much more aware\nI'm becoming this all I want to do\nIs be more like me and be less like you\n\nI've become so numb I can't feel you there\nI'm tired of being what you want me to be\nI've become so numb I can't feel you there\nI'm tired of being what you want me to be"
    ),
    SongModel(
        0,
        "Radioactive",
        "Imagine Dragons",
        "NIGHT VISIONS",
        "I'm waking up to ash and dust\nI wipe my brow, and I sweat my rust\nI'm breathing in the chemicals\n\nI'm breaking in and shaping up\nThen checking out on the prison bus\nThis is it, the apocalypse\nWhoa\n\nI'm waking up\nI feel it in my bones\nEnough to make my system blow\nWelcome to the new age, to the new age\nWelcome to the new age, to the new age\n\nWhoa-oh-oh-oh, oh\nWhoa-oh-oh-oh, I'm\nRadioactive, radioactive\n\nWhoa-oh-oh-oh, oh\nWhoa-oh-oh-oh, I'm\nRadioactive, radioactive\n\nI raise my flag, and dye my clothes\nIt's a revolution, I suppose\nWe're painted red to fit right in\nWhoa\n\nI'm breaking in and shaping up\nThen checking out on the prison bus\nThis is it, the apocalypse\nWhoa\n\nI'm waking up\nI feel it in my bones\nEnough to make my system blow\nWelcome to the new age, to the new age\nWelcome to the new age, to the new age\n\nWhoa-oh-oh-oh, oh\nWhoa-oh-oh-oh, I'm\nRadioactive, radioactive\n\nWhoa-oh-oh-oh, oh\nWhoa-oh-oh-oh, I'm\nRadioactive, radioactive\n\nAll systems go\nThe sun hasn't died\nDeep in my bones\nStraight from inside\n\nI'm waking up\nI feel it in my bones\nEnough to make my system blow\nWelcome to the new age, to the new age\nWelcome to the new age, to the new age\n\nWhoa-oh-oh-oh, oh\nWhoa-oh-oh-oh, I'm\nRadioactive, radioactive\n\nWhoa-oh-oh-oh, oh\nWhoa-oh-oh-oh, I'm\nRadioactive, radioactive"
    ),
    SongModel(
        0,
        "Smells Like Teen Spirit",
        "Nirvana",
        "FROM THE MUDDY BANKS OF THE WISHKAH",
        "Load up on guns and bring your friends\nIt's fun to lose and to pretend\nShe's over-bored and self-assured\nOh no, I know a dirty word\n\nHello, hello, hello, how low?\nHello, hello, hello, how low?\nHello, hello, hello, how low?\nHello, hello, hello\n\nWith the lights out, it's less dangerous\nHere we are now, entertain us\nI feel stupid and contagious\nHere we are now, entertain us\n\nA mulatto, an albino\nA mosquito, my libido\nYeah, hey, yay\n\nI'm worse at what I do best\nAnd for this gift I feel blessed\nOur little group has always been\nAnd always will until the end\n\nHello, hello, hello, how low?\nHello, hello, hello, how low?\nHello, hello, hello, how low?\nHello, hello, hello\n\nWith the lights out, it's less dangerous\nHere we are now, entertain us\nI feel stupid and contagious\nHere we are now, entertain us\n\nA mulatto, an albino\nA mosquito, my libido\nYeah, hey, yay\n\nAnd I forget just why I taste\nOh yeah, I guess it makes me smile\nI found it hard, it's hard to find\nOh well, whatever, nevermind\n\nHello, hello, hello, how low?\nHello, hello, hello, how low?\nHello, hello, hello, how low?\nHello, hello, hello\n\nWith the lights out, it's less dangerous\nHere we are now, entertain us\nI feel stupid and contagious\nHere we are now, entertain us\n\nA mulatto, an albino\nA mosquito, my libido\n\nA denial, a denial\nA denial, a denial\nA denial, a denia\nA denial, a denial\nA denial"
    ),
    SongModel(
        0,
        "Fireflies",
        "Owl City",
        "OCEAN EYES",
        "You would not believe your eyes\nIf ten million fireflies\nLit up the world as I fell asleep\n\n'Cause they'd fill the open air\nAnd leave teardrops everywhere\nYou'd think me rude, but I would just stand and stare\n\nI'd like to make myself believe\nThat planet Earth turns slowly\nIt's hard to say that I'd rather stay awake when I'm asleep\n'Cause everything is never as it seems\n\n'Cause I'd get a thousand hugs\nFrom ten thousand lightning bugs\nAs they try to teach me how to dance\n\nA fox-trot above my head\nA sock-hop beneath my bed\nA disco ball is just hanging by a thread\n\nI'd like to make myself believe\nThat planet Earth turns slowly\nIt's hard to say that I'd rather stay awake when I'm asleep\n'Cause everything is never as it seems\n\nLeave my door open just a crack\n'Cause I feel like such an insomniac\nWhy do I tire of counting sheep?\nWhen I'm far too tired to fall asleep\n\nTo ten million fireflies\nI'm weird 'cause I hate goodbyes\nI got misty eyes as they said farewell\n\nBut I'll know where several are\nIf my dreams get real bizarre\n'Cause I saved a few, and I keep them in a jar\n\nI'd like to make myself believe\nThat planet Earth turns slowly\nIt's hard to say that I'd rather stay awake when I'm asleep\n'Cause everything is never as it seems\n\nI'd like to make myself believe\nThat planet Earth turns slowly\nIt's hard to say that I'd rather stay awake when I'm asleep\n'Cause everything is never as it seems\n\nI'd like to make myself believe\nThat planet Earth turns slowly\nIt's hard to say that I'd rather stay awake when I'm asleep\nBecause my dreams are bursting at the seams"
    ),
    SongModel(
        0,
        "Never Let Me Down",
        "VIZE & Tom Gregory",
        "Stand Alone",
        "You've got a hold on me\nYou take control of me\nJust don't let go of me\nI don't wanna lose you\n\nYou've got my head spinning\nQuit all the bad thinking\nWant you to last with me\nI don't wanna lose you\n\nHold on me, take control of me\nDon't let go of me, oh, never let me down\n\nDown, down, d-d-d-d-down\nDown, d-d-d-d-down\nDown, d-d-d-d, never me let me down\n\nGive me higher ground\nBaby, lift me higher now, now\nTurn me right around\nNever let me down\n\nGive me higher ground\nBaby, lift me higher now, now\nTurn me right around\nNever let me down\n\nDown, down, d-d-d-d-down\nDown, d-d-d-d-down\nDown, d-d-d-d, never me let me down\nDown, down, d-d-d-d-down\nDown, d-d-d-d-down\nDown, d-d-d-d, never me let me down\n\nDon't have to say nothing\nYou've got my mind running\nFeel like I'm free falling\nI don't wanna lose you\n\nYou've got my head spinning\nQuit all the bad thinking\nWant you to last with me\nI don't wanna lose you\n\nHold on me, take control of me\nDon't let go of me, oh, never let me down\n\nDown, down, d-d-d-d-down\nDown, d-d-d-d-down\nDown, d-d-d-d, never me let me down\n\nGive me higher ground\nBaby, lift me higher now, now\nTurn me right around\nNever let me down\n\nGive me higher ground\nBaby, lift me higher now, now\nTurn me right around\nNever let me down\n\nDown, down, d-d-d-d-down\nDown, d-d-d-d-down\nDown, d-d-d-d, never me let me down\nDown, down, d-d-d-d-down\nDown, d-d-d-d-down\nDown, d-d-d-d, never me let me down\n\nGive me higher ground\nBaby, lift me higher now, now\nTurn me right around\nNever let me down\n\nGive me higher ground\nBaby, lift me higher now, now\nTurn me right around\nNever let me down\n\nDown, down, d-d-d-d-down\nDown, d-d-d-d-down\nDown, d-d-d-d, never me let me down\nDown, down, d-d-d-d-down\nDown, d-d-d-d-down\nDown, d-d-d-d, never me let me down"
    ),
    SongModel(
        0,
        "ily (i love you baby)",
        "Surf Mesa",
        "Stand Alone",
        "I love you, baby\nAnd if it's quite all right\nI need you, baby\nTo warm these lonely nights\nI love you, baby\nTrust in me when I say\n\nI love you, baby\nAnd if it's quite all right\nI need you, baby\nTo warm these lonely nights\nI love you, baby\nTrust in me when I say\n\nI love you\n\nI love you, baby\nAnd if it's quite all right\nI need you, baby\nTo warm these lonely nights\nI love you, baby\nTrust in me when I say\n\nI love you\nI love you\nI love you\n\nI love you, baby\nAnd if it's quite all right\nI need you, baby\nTo warm these lonely nights\nI love you, baby\nTrust in me when I say\n\nI love you, baby\nAnd if it's quite all right\nI need you, baby\nTo warm these lonely nights\nI love you, baby\nTrust in me when I say\n\nI love you\n\nI love you, baby\nAnd if it's quite all right\nI need you, baby\nTo warm these lonely nights\nI love you, baby\nTrust in me when I say\n\nI love you, baby\nAnd if it's quite all right\nI need you, baby\nTo warm these lonely nights\nI love you, baby\nTrust in me when I say"
    ),
    SongModel(
        0,
        "21 Guns",
        "Green Day",
        "AMERICAN IDIOT",
        "Do you know what's worth fighting for?\nWhen it's not worth dying for?\nDoes it take your breath away and you feel yourself suffocating?\nDoes the pain weigh out the pride?\nAnd you look for a place to hide?\nDid someone break your heart inside, you're in ruins\n\nOne, 21 Guns\nLay down your arms\nGive up the fight\nOne, 21 Guns\nThrow up your arms into the sky\nYou and I ...\n\nWhen you're at the end of the road\nAnd you lost all sense of control\nAnd your thoughts have taken their toll\nWhen your mind breaks the spirit of your soul\nYour faith walks on broken glass and the hangover doesn't pass\nNothing's ever built to last, you're in ruins\n\nOne, 21 Guns\nLay down your arms\nGive up the fight\nOne, 21 Guns\nThrow up your arms into the sky\nYou and I ...\n\nDid you try to live on your own?\nWhen you burned down the house and home?\nDid you stand too close to the fire?\nLike a liar looking for forgiveness from a stone\nWhen it's time to live and let die\nAnd you can't get another try\nSomething inside this heart has died, you're in ruins\n\nOne, 21 Guns\nLay down your arms\nGive up the fight\nOne, 21 Guns\nThrow up your arms into the sky\nOne, 21 Guns\nLay down your arms\nGive up the fight\nOne, 21 Guns\nThrow up your arms into the sky\n\nYou and I"
    ),
    SongModel(
        0,
        "In the End",
        "Linkin Park",
        "RECHARGED",
        "It starts with\nOne thing I don't know why\nIt doesn't even matter how hard you try\nKeep that in mind I designed this rhyme\nTo explain in due time\n\nAll I know\nTime is a valuable thing\nWatch it fly by as the pendulum swings\nWatch it count down to the end of the day\nThe clock ticks life away\n\nIt's so unreal\nDidn't look out below\nWatch the time go right out the window\nTrying to hold on, but didn't even know\nOr wasted it all just to watch you go\n\nI kept everything inside\nAnd even though I tried, it all fell apart\nWhat it meant to me will eventually be\nA memory of a time when\n\nI tried so hard and got so far\nBut in the end it doesn't even matter\nI had to fall to lose it all\nBut in the end it doesn't even matter\n\nOne thing, I don't know why\nIt doesn't even matter how hard you try\nKeep that in mind I designed this rhyme\nTo remind myself how\n\nI tried so hard\nIn spite of the way you were mocking me\nActing like I was part of your property\nRemembering all the times you fought with me\nI'm surprised\n\nIt got so far\nThings aren't the way they were before\nYou wouldn't even recognize me anymore\nNot that you knew me back then\nBut it all comes back to me in the end\n\nYou kept everything inside\nAnd even though I tried, it all fell apart\nWhat it meant to me will eventually be\nA memory of a time when\n\nI tried so hard and got so far\nBut in the end it doesn't even matter\nI had to fall to lose it all\nBut in the end it doesn't even matter\n\nI've put my trust in you\nPushed as far as I can go\nAnd for all this\nThere's only one thing you should know\n\nI've put my trust in you\nPushed as far as I can go\nAnd for all this\nThere's only one thing you should know\n\nI tried so hard and got so far\nBut in the end it doesn't even matter\nI had to fall to lose it all\nBut in the end it doesn't even matter"
    ),
    SongModel(
        0,
        "Lovefool",
        "twocolors",
        "Stand Alone",
        "Love me, love me\nSay that you love me\nFool me, fool me\nGo on and fool me\n\nDear, I fear we're facing a problem\nYou love me no longer, I know\nAnd maybe there is nothing that I can do\nTo make you do\n\nMama tells me, I shouldn't bother\nThat I ought to stick to another man\nA man that surely deserves me\nBut I think you do\n\nSo I cry and I pray, and I beg for you to\n\nLove me, love me\nSay that you love me\nFool me, fool me\nGo on and fool me\nLove me, love me\nPretend that you love me\nLeave me, leave me\nJust say that you need me\n\nLove me, love me\nFool me, fool me\nLove me, love me\nFool me, fool me\n\nLately, I have desperately pondered\nSpent my nights awake and I wondered\nWhat I could have done in another way\nTo make you stay\n\nReason will not reach a solution\nI will end up lost in confusion\nI don't care if you really care\nAs long as you don't go\n\nSo I cry, and I pray, and I beg for you to\n\nLove me, love me\nSay that you love me\nFool me, fool me\nGo on and fool me\nLove me, love me\nPretend that you love me\nLeave me, leave me\nJust say that you need me\n\nLove me, love me\nFool me, fool me\nLove me, love me\nFool me, fool me\n\nOh, I cry and I pray and I beg for you to love me\nI cry and I pray and I beg for you to love me\n\nLove me, love me\nFool me, fool me\nLove me, love me\nLove me, love me\nSay that you love me\n\nLove me, love me (for you to love me)\nFool me, fool me (for you to love me)\nLove me, love me (for you to love me)\nLove me, love me\nSay that you love me"
    ),
    SongModel(
        0,
        "Mo Bamba",
        "Sheck Wes",
        "MUDBOY",
        "16yrold\nBitch\nDaytrip took it to ten\n\nI got hoes...\nCallin', a young nigga phone (Ring, ring)\nWhere's Ali with the motherfuckin' dope? (bitch, bitch)\nI be ballin' like a mo'fuckin' pro (Like a, huh, like a, huh)\nI be ballin' like my nigga Mo (Bamba, bitch)\nSheck Wes, I ain't a mo'fuckin' joke (haha, hahahahaha)\nSteph Wes stay with the fuckin' pole (pa, pa, pa-pa)\nYou fuck around and get poled (you get poled, bitch)\n\n'Cause I got hoes (Too many fucking hoes)\nCallin' a young nigga phone (Ring-ring, ring, ring-ring, ring, ring-ring)\nWhere's Ali with the (bitch with the) mo'fuckin' dope? (huh)\nI be ballin' like a mo'fuckin' pro (like a mo'fuckin' pro)\nI be ballin' like my nigga Mo (Bamba, Bamba)\nSheck Wes got so many flows (I do it all)\nCall me Drake how a nigga contro...\n\nOh! Fuck! Shit! Bitch!\nYoung Sheck Wes and I'm getting really rich (ching-ching)\nSee how I caught it 'cause I'm really with the shits (bang-bang)\nSee me in the streets and I be really with a (cling, cling), with a\nBad bitch (bitch), niggas straight rocking (rock)\nNiggas straight see me, when they see me, they be coppin' (what?)\nI'm the best drug dealer, nigga, come and cop it (got it)\nYoung Sheck Wes, I'm like the fuckin' Green Goblin (Hahaha)\n\nI got hoes (Hoes)\nCallin', a young nigga phone, phone (bitch)\nWhere's Ali with the motherfucking dope?\n(With the motherfucking dope)\nDope (with the motherfucking dope)\nMotherfucking dope (bitch)\nWith the dope (getting rich), with my bros (bitch, shit)\nI fucked your hoe (shit)\nAnd she ain't even let you know (she fucked up)\n\nDamn, this nigga nice, fuck is you talking about?\n('Cause I got) bitch (hoes)\nAnd my nigga One-Six, my nigga\nAli, the Daytrip nigga, fuck is niggas talking about?\nI got hoes, shit\nYoung Sheck Wes, I do it on the go"
    ),
    SongModel(
        0,
        "Living in a Ghost Town",
        "The Rolling Stones",
        "HONK",
        "Woah, woah\n\nI'm a ghost\nLivin' in a ghost town\nI'm a ghost\nLivin' in a ghost town\n\nYou can come look for me\nBut I can't be found\nYou can search for me\nI had to go underground\n\nLife was so beautiful\nThen we all got locked down\nFeel like a ghost\nLiving in a ghost town, yeah\n\nOnce this place was hummin'\nAnd the air was full of drummin'\nThe sound of cymbals crashin'\nGlasses were all smashin'\nTrumpets were all screamin'\nSaxophones were blarin'\nNobody was carin'\nIf it's day or not\n\nWoah, woah\n\nI'm a ghost\nLivin' in a ghost town\nI'm goin' nowhere\nShut up all alone\nSo much time to lose\nJust starin' at my phone\n\nEvery night I am dreamin'\nThat you'll come and creep in my bed\nPlease let this be over\nNot stuck in a world without end\nMy friend\n\nWoah\nWoah, woah\n\nPreachers were all preachin'\nCharities beseechin'\nPoliticians dealin'\nThieves were happy stealin'\nWidows were all weepin'\nThere's no beds for us to sleep in\nAlways had the feelin'\nIt will all come tumblin' down\n\nI'm a ghost\nLivin' in a ghost town\nYou can look for me\nBut I can't be found\n\nWoah\n\nWe're all livin' in a ghost town (Woah)\nOh, livin' in a ghost town (Woah)\nWe were so beautiful (Woah)\nI was your man about town (Woah)\n\nLivin' in this ghost town (Woah)\nAin't havin' any fun (Woah)\nIf I wanna party (Woah)\nIt's a party of one (Woah, woah)"
    )
)